Develop audit big data
Flexberry/ember-flexberry-security pull request #20
Opened 2021-07-03 17:26 UTC by AntonIV8

2021-07-06 05:48 UTC, kuzkok requested changes

2021-07-06 05:48 UTC, kuzkok commented on addon/locales/en/forms/new-platform-flexberry-audit-big-data-audit-record-e.js
> +export default {
Заголовки сделать красивые, названия полей раздробить на отдельные слова.

2021-07-06 05:48 UTC, kuzkok commented on addon/adapters/new-platform-flexberry-audit-big-data-audit-record.js
> +    const auditBigDataOdataHost = config.APP.bpmBackendUrls.auditBigDataOdata || '';
почему bpmBackendUrls?

2021-07-06 05:48 UTC, kuzkok commented on addon/locales/en/forms/new-platform-flexberry-audit-big-data-audit-record-l.js
> +export default {
Тоже перевод не закончен

2021-07-06 05:48 UTC, kuzkok commented on addon/routes/new-platform-flexberry-audit-big-data-audit-record-e.js
> +    let _this = this;
зачем так делать?

2021-07-06 05:48 UTC, kuzkok commented on addon/routes/new-platform-flexberry-audit-big-data-audit-record-e.js
> +    store.queryRecord(modelName, builder.build()).then(function (ratifyRecord) {
arrowFunction

2021-07-06 05:48 UTC, kuzkok commented on addon/routes/new-platform-flexberry-audit-big-data-audit-record-e.js
> +    const headAuditEntityKey = model.get('id');
точно  get('id') а не get('headAuditEntity')?

2021-07-06 05:48 UTC, kuzkok commented on app/templates/components/audit-fields-view.hbs
> +<table class="object-list-view ui unstackable celled {{if readonly 'readonly'}} table">
а в каком случае audit-fields может быть не readonly?

2021-07-06 06:01 UTC, AntonIV8 commented on addon/routes/new-platform-flexberry-audit-big-data-audit-record-e.js
> +    const headAuditEntityKey = model.get('id');
тут обрабатываем основную запись. В данном случае ищется ratify запись, соответствующая основной. headAuditEntity это поле актуальное для ratify записи, в нем как раз и записан id основной записи

2021-07-06 06:02 UTC, NicholasNoise commented on addon/mixins/regenerated/models/new-platform-flexberry-audit-big-data-audit-record.js
> +  operationType: DS.attr('string'),
Неправильный тип

2021-07-06 06:02 UTC, NicholasNoise commented on app/adapters/new-platform-flexberry-audit-big-data-audit-record.js
> +export { default } from 'ember-flexberry-security/adapters/new-platform-flexberry-audit-big-data-audit-record';
Пустая строка в конце файла

2021-07-06 06:02 UTC, NicholasNoise commented on app/serializers/new-platform-flexberry-audit-big-data-audit-record.js
> +export { default } from 'ember-flexberry-security/serializers/new-platform-flexberry-audit-big-data-audit-record';
+1

2021-07-06 06:02 UTC, NicholasNoise commented on app/transforms/new-platform-flexberry-audit-big-data-execution-status.js
> +
А тут лишняя (судя по всему)

2021-07-06 06:02 UTC, AntonIV8 commented on addon/routes/new-platform-flexberry-audit-big-data-audit-record-e.js
> +    let _this = this;
В then вроде как this потеряется, если его не закэшировать таким образом

2021-07-06 06:05 UTC, AntonIV8 commented on addon/mixins/regenerated/models/new-platform-flexberry-audit-big-data-audit-record.js
> +  operationType: DS.attr('string'),
Неправильный тип чего ?

2021-07-06 06:44 UTC, NicholasNoise commented on addon/mixins/regenerated/models/new-platform-flexberry-audit-big-data-audit-record.js
> +  operationType: DS.attr('string'),
Свойства, в выделенной строки ес-но (чего же ещё?):
`operationType: DS.attr('new-platform-flexberry-audit-big-data-audit-operation-type),

2021-07-06 17:37 UTC, KollegOFF commented on addon/adapters/new-platform-flexberry-audit-big-data-audit-record.js
> +    const auditBigDataOdataHost = config.APP.bpmBackendUrls.auditBigDataOdata || '';
А `ember-get-config` не завёлся?

2021-07-06 17:43 UTC, KollegOFF commented on addon/routes/new-platform-flexberry-audit-big-data-audit-record-e.js
> +    store.queryRecord(modelName, builder.build()).then(function (ratifyRecord) {
И ещё добавить `return store.queryRecord(...)`, чтобы шаблон этого запроса дождался.

2021-07-06 17:55 UTC, KollegOFF commented on addon/routes/new-platform-flexberry-audit-big-data-audit-record-e.js
> +    store.queryRecord(modelName, builder.build()).then(function (ratifyRecord) {
А `ratifyRecord` всегда найдётся, или её может ещё не быть?

2021-07-06 17:58 UTC, KollegOFF commented on app/templates/components/audit-fields-view.hbs
> +<table class="object-list-view ui unstackable celled {{if readonly 'readonly'}} table">
Нужно обойтись без класса `object-list-view`, если на нём есть какие то нужные стили, добавить их со своим классом.

2021-07-06 18:11 UTC, KollegOFF commented on addon/helpers/audit-fields-deserializer.js
> +}
Это лучше сделать утилитой, хелперы нужны для шаблонов.

2021-07-06 18:11 UTC, KollegOFF commented on addon/routes/new-platform-flexberry-audit-big-data-audit-record-l.js
> +      conditions.pushObject(ratifyLimitFunction);
Либо объявить `conditions` как `Ember.A()`, либо работать с ним как с обычным массивом.
Лучше второе, потому что специальный массив здесь не нужен.

2021-07-06 18:11 UTC, KollegOFF commented on app/templates/new-platform-flexberry-audit-big-data-audit-record-e.hbs
> +      <button type="submit" class="ui button close-button" {{action 'close'}}>
```suggestion
      <button type="button" class="ui button close-button" {{action 'close'}}>
```

2021-07-07 04:23 UTC, AntonIV8 commented on addon/routes/new-platform-flexberry-audit-big-data-audit-record-e.js
> +    store.queryRecord(modelName, builder.build()).then(function (ratifyRecord) {
Может не быть, но тогда ведь then не сработает и статус не изменится ?

2021-07-07 04:25 UTC, AntonIV8 commented on addon/mixins/regenerated/models/new-platform-flexberry-audit-big-data-audit-record.js
> +  operationType: DS.attr('string'),
Предполагается, что это поле открыто для кастомизации и может содержать не только Enum значение

2021-07-07 14:12 UTC, NicholasNoise approved these changes

2021-07-08 07:40 UTC, KollegOFF commented on addon/mixins/regenerated/models/new-platform-flexberry-audit-big-data-audit-record.js
> +  operationType: DS.attr('string'),
А я не понял, что тут кастомизировать?

2021-07-08 07:45 UTC, KollegOFF commented on addon/routes/new-platform-flexberry-audit-big-data-audit-record-e.js
> +    store.queryRecord(modelName, builder.build()).then(function (ratifyRecord) {
К сожалению, `then` сработает, но `ratifyRecord` там будет `undefined`, это проблемы `ember-fleberry-data`.

2021-07-08 07:47 UTC, KollegOFF commented on addon/routes/new-platform-flexberry-audit-big-data-audit-record-l.js
> +      let isComplexPredicate = conditions.get('length') > 1;
```suggestion
      let isComplexPredicate = conditions.length > 1;
```

2021-07-09 11:03 UTC, kuzkok commented on addon/locales/ru/forms/new-platform-flexberry-audit-big-data-audit-record-e.js
> +  'objectType-caption': 'Тип Объекта',
А зачем каждое слово с большой буквы? это в английском так принято, на русском только первое в предложении.

2021-07-09 11:37 UTC, kuzkok approved these changes

2021-07-11 17:36 UTC, KollegOFF approved these changes

2021-07-11 17:39 UTC, merged