Add parent roles display
Flexberry/ember-flexberry-security pull request #46
Opened 2022-10-01 13:17 UTC by Anisimova2020

Добавлена загрузка всех связей между ролями, по этим связям строится иерархия.
На основании этой иерархии чекбоксам из столбца "наследованные роли" формируется вычислимое свойство для определения состояния (для этого для таких чекбоксов добавлен особый тип объектов).

Fixes #45.

2022-10-07 06:41 UTC, bratchikov requested changes

2022-10-07 06:41 UTC, bratchikov commented on addon/mixins/security-get-agent-roles-route.js
> +        // TODO: filter 'not model.id', 'not All users'.
Если хочется оставить какое-то TODO, значит надо завести нормальное issue, а TODO убрать.

2022-10-07 06:42 UTC, bratchikov commented
Нужно сразу добавить GitHub Action который будет собирать проект.

2022-11-18 05:38 UTC, DubrovinPavel commented on addon/mixins/security-get-agent-roles-route.js
> +        // TODO: filter 'not model.id', 'not All users'.
Добавил в список задач

2022-11-18 05:40 UTC, merged